<a href="https://colab.research.google.com/github/surajsrivathsa/ovgu_deeplearning/blob/master/Assignment_7_Assortment_Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Deep Learning programming task

**Assignment 7:** Assortment Programming Puzzels

**Team members:**
1. Sanjeeth Busnur Indushekar: 224133 : sanjeeth.busnur@st.ovgu.de
2. Aditya Dey : 230580 : aditya.dey@st.ovgu.de
3. Suraj Shashidhar: 230052 : suraj.shashidhar@st.ovgu.de

# Tasks to be done:

**Task 5 was not completed, Rest of the tasks were completed**

![alt text](https://drive.google.com/uc?id=1p4Kx2OZv8hqXtdspGMcnzdb0PIWFBASE)


In [0]:
import os
%tensorflow_version 2.x
import tensorflow as tf
from sklearn import preprocessing
from google.colab import files
from google.colab import drive
import matplotlib.pyplot as plt
import pandas as pd
import copy
import numpy as np

In [2]:
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image
from tensorflow.keras import datasets, layers, models
from tensorflow.keras import initializers
import tensorboard
import time
from datetime import datetime
from keras import backend as K
from prepare_data import parse_seq
import pickle

Using TensorFlow backend.


In [0]:
# 448 is the longest length sequence there are 31k sequences

In [3]:
  print(os.getcwd())
  print(tf.__version__)

/content
2.2.0


In [0]:
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [4]:

path = '.'
 
files = os.listdir(path)
for name in files:
    print(name)

.config
shakespeare_input.txt
skp_vocab
skp.tfrecords
prepare_data.py
__pycache__
sample_data


# **Task 1**: 
Given a 2D tensor of shape (?, n), extract the k (k <= n) highest values for each row into a tensor of shape (?, k). Hint: There might be a function to get the “top k” values of a tensor.

In [41]:
input_tnsr_t1 = tf.Variable(tf.keras.initializers.GlorotNormal(seed = 1)(shape=[16, 16]))
input_tnsr_t1

<tf.Variable 'Variable:0' shape=(16, 16) dtype=float32, numpy=
array([[ 0.03599551, -0.14012113,  0.17939186, -0.2241995 , -0.25859192,
        -0.11344741, -0.01083392,  0.13301323, -0.00425996, -0.39874047,
         0.48727453, -0.3916559 ,  0.10636404,  0.1940137 , -0.06120357,
        -0.1483257 ],
       [-0.0474022 , -0.16743772, -0.00250254, -0.06109133,  0.08316933,
         0.01863756, -0.05121751,  0.33412674,  0.19457917,  0.29651564,
         0.07020745,  0.20923188,  0.00870483, -0.3769552 , -0.04677309,
         0.00573805],
       [ 0.15328243, -0.24259292, -0.08504364, -0.11215784, -0.29976562,
        -0.24337359, -0.16631705, -0.32558355,  0.46128425,  0.04590841,
         0.1541892 ,  0.43880546,  0.20568156, -0.08913616,  0.21326609,
        -0.20274375],
       [ 0.11914316, -0.11068519,  0.08054616,  0.1384888 , -0.4070555 ,
        -0.15359019, -0.18134585, -0.13427472,  0.08665706, -0.15112805,
        -0.35246122,  0.12724638,  0.23564412,  0.15365699,  0.44361

In [0]:
@tf.function
def topk(inp_tensor, k, sort):
  return tf.math.top_k(inp_tensor, k, sort)

In [0]:
topk(input_tnsr_t1, 2, True)

TopKV2(values=<tf.Tensor: shape=(16, 2), dtype=float32, numpy=
array([[0.48727453, 0.1940137 ],
       [0.33412674, 0.29651564],
       [0.46128425, 0.43880546],
       [0.44361848, 0.23564412],
       [0.30533567, 0.27963844],
       [0.5550816 , 0.39712387],
       [0.51683193, 0.3538438 ],
       [0.51508737, 0.34444094],
       [0.30141658, 0.28461596],
       [0.3702066 , 0.3078747 ],
       [0.42835367, 0.3826073 ],
       [0.27436855, 0.22841172],
       [0.44356868, 0.30833662],
       [0.51057893, 0.3908865 ],
       [0.41722775, 0.28793982],
       [0.3917093 , 0.34242094]], dtype=float32)>, indices=<tf.Tensor: shape=(16, 2), dtype=int32, numpy=
array([[10, 13],
       [ 7,  9],
       [ 8, 11],
       [14, 12],
       [ 1,  2],
       [ 4,  2],
       [ 6,  2],
       [ 1,  5],
       [14, 10],
       [10,  4],
       [13, 14],
       [ 9,  4],
       [ 3,  8],
       [10,  0],
       [ 8, 11],
       [14, 10]], dtype=int32)>)

# **Task 2:**
Given a tensor of shape (?, n), find the argmax in each row and return a new tensor that contains a 1 in each of the argmax’ positions, and 0s everywhere else.

Use the same method used in assigment 6/7

https://www.tensorflow.org/api_docs/python/tf/sequence_mask

In [0]:
inp_tensor = tf.random.uniform((10,10),minval=-10, maxval=10, dtype=tf.dtypes.int32)

In [0]:
def maskMatrix(inp_tensor):
  max_indices = tf.TensorArray(tf.dtypes.int64, 0, True)
  for x, i in enumerate(tf.math.argmax(inp_tensor, axis= 1).numpy()):
    max_indices = max_indices.write(x, [x,i])
  values = tf.ones(inp_tensor.shape[0], tf.dtypes.int64)
  return tf.sparse.to_dense(tf.sparse.SparseTensor(max_indices.stack(), values, inp_tensor.shape))

In [0]:
maskMatrix(inp_tensor)

<tf.Tensor: shape=(10, 10), dtype=int64, numpy=
array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])>

# **Task 3**
As in 1., but instead of “extracting” the top k values, create a new tensor with shape (?, n) where all but the top k values for each row are zero. Try doing this with a 1D tensor of shape (n,) (i.e. one row) first. Getting it right for a 2D tensor is more tricky; consider this a bonus. Hint: You should look for a way to “scatter” a tensor of values into a different tensor. For two or more dimensions, you need to think carefully about the indices.

References

https://stackoverflow.com/questions/49966402/using-tensorflows-top-k-and-scatter-nd
https://stackoverflow.com/questions/52996505/using-scatter-nd-with-top-k-output

In [0]:
@tf.function
def topk(inp_tensor, k, sort):
  return tf.math.top_k(inp_tensor, k, sort)

In [0]:
@tf.function
def extract_top_K(inp_tensor, k):
  top_k_values, top_k_indices = topk(inp_tensor, k, True)
  num_rows = top_k_indices.shape[0]
  row_range = tf.range(num_rows)
  row_tensor = tf.tile(row_range[:,None], (1, k))
  top_k_row_col_indices = tf.stack([row_tensor, top_k_indices], axis=2)
  print(top_k_row_col_indices)
  print(top_k_values)
  return tf.scatter_nd(top_k_row_col_indices, top_k_values, inp_tensor.shape)

In [0]:
topk_matrix = extract_top_K(inp_tensor, 4)
topk_matrix

Tensor("stack:0", shape=(10, 4, 2), dtype=int32)
Tensor("PartitionedCall:0", shape=(10, 4), dtype=int32)


<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 2,  0,  0,  9,  2,  0,  0,  6,  0,  0],
       [ 7,  0,  0,  9,  0,  7,  0,  0,  0,  7],
       [ 0,  0,  0,  6,  0,  0, -1,  7,  4,  0],
       [ 0,  0,  0,  2,  2,  0,  8,  0,  7,  0],
       [ 0,  0,  2,  4,  0,  0,  9,  7,  0,  0],
       [ 0,  5,  0,  0,  5,  0,  0,  7,  1,  0],
       [ 0,  9,  3,  0,  3,  0,  0,  0,  7,  0],
       [ 0,  0,  0,  0,  4,  5,  4,  0,  6,  0],
       [ 0,  5,  0,  0,  0,  8,  6,  0,  2,  0],
       [ 0,  9, -1,  0,  3,  0,  0,  2,  0,  0]], dtype=int32)>

# **Task 4**
Implement an exponential moving average. That is, given a decay rate a and an input tensor of length T, create a new length T tensor where new[0] = input[0] and new[t] = a * new[t-1] + (1-a) * input[t] otherwise. Do not use tf.train.ExponentialMovingAverage.

In [68]:
inp_tensor2 = tf.random.uniform([10],minval=-10, maxval=10, dtype=tf.dtypes.float32)
inp_tensor2



<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 1.1139183,  6.127817 ,  1.5861082,  5.5715227,  8.066624 ,
       -9.228535 , -7.4225616,  5.852726 ,  0.6180906, -1.3401985],
      dtype=float32)>

In [0]:
@tf.function
def exp_mov_avg(inp_tensor, a):
  a = tf.cast(a, tf.dtypes.float32)
  new_tensor = tf.TensorArray(tf.dtypes.float32, size = 0, dynamic_size=True)
  new_tensor = new_tensor.write(0, inp_tensor[0])
  for t in tf.range(1, inp_tensor.shape[0]):
    new_tensor_stack = new_tensor.stack()
    new_val = tf.squeeze(tf.add(tf.multiply(a, new_tensor_stack[t-1]), tf.multiply(tf.subtract(1.0,a), inp_tensor[t])))
    new_tensor = new_tensor.write(t, new_val)
  return new_tensor.stack()

In [73]:
ema = exp_mov_avg(inp_tensor2, 0.4)
ema

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 1.1139183 ,  4.1222577 ,  2.600568  ,  4.383141  ,  6.5932307 ,
       -2.8998284 , -5.613468  ,  1.2662485 ,  0.8773538 , -0.45317766],
      dtype=float32)>

# **Task 5**

***Task 5 was not completed***

In [48]:
input_tnsr_t5 = tf.Variable(tf.keras.initializers.GlorotNormal(seed = 1)(shape=[10, 5]))
input_tnsr_t5

<tf.Variable 'Variable:0' shape=(10, 5) dtype=float32, numpy=
array([[ 0.05257481, -0.20466001,  0.2620186 , -0.32746434, -0.37769768],
       [-0.16570054, -0.01582395,  0.19427827, -0.00622208, -0.5823977 ],
       [ 0.71171   , -0.57205003,  0.15535462,  0.28337514, -0.08939353],
       [-0.21664353, -0.06923535, -0.24455844, -0.0036552 , -0.0892296 ],
       [ 0.12147658,  0.0272219 , -0.07480796,  0.48802334,  0.28420106],
       [ 0.43308884,  0.10254454,  0.30560273,  0.01271421, -0.55057836],
       [-0.06831647,  0.00838095,  0.22388332, -0.35432962, -0.12421418],
       [-0.16381702, -0.43783572, -0.35546988, -0.24292159, -0.47554523],
       [ 0.6737488 ,  0.06705352,  0.22520775,  0.6409164 ,  0.30041716],
       [-0.1301917 ,  0.31149507, -0.2961262 ,  0.17401972, -0.16166607]],
      dtype=float32)>

In [60]:
t = tf.constant([[[1, -1, 1], [2, -2, 2]],
                 [[3, -3, 3], [-9, 7, 9]],
                 [[5, -5, 5], [6, -6, 6]]])
tf.shape(t)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 2, 3], dtype=int32)>

In [66]:
tf.slice(t, [1, 0, 0], [1, 1, 3])  # [[[3, 3, 3]]]
tf.slice(t, [2, 1, 0], [1, 1, 2])  # [[[3, 3, 3],
                                   #   [4, 4, 4]]]

<tf.Tensor: shape=(1, 1, 2), dtype=int32, numpy=array([[[ 6, -6]]], dtype=int32)>

In [50]:
tf.slice(input_tnsr_t5, begin=0, size=4, name=None)

InvalidArgumentError: ignored

In [0]:
ema = tf.train.ExponentialMovingAverage(decay=0.9)

In [78]:
input_tnsr_t5 = tf.Variable(tf.keras.initializers.GlorotNormal(seed = 1)(shape=[10, ]))
input_tnsr_t5

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=
array([ 0.04553112, -0.17724077,  0.22691475, -0.28359243, -0.32709578,
       -0.14350088, -0.01370394,  0.16824992, -0.00538848, -0.5043712 ],
      dtype=float32)>

In [79]:
training_op = ema.apply([input_tnsr_t5])

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.


In [80]:
shadow_var0_name = ema.average_name(input_tnsr_t5)

AttributeError: ignored

# **Task 6**
Given three integer tensors x, y, z all of the same (arbitrary) shape, create a new tensor that takes values from y where x is even and from z where x is odd.

In [0]:
x = tf.random.uniform([10],minval=0, maxval=10, dtype=tf.dtypes.int32)
y = tf.random.uniform([10],minval=0, maxval=10, dtype=tf.dtypes.int32)
z = tf.random.uniform([10],minval=0, maxval=10, dtype=tf.dtypes.int32)

In [0]:
def new_tensor_gen(x,y,z):
  new_tensor = tf.TensorArray(tf.dtypes.int32, 0, True)
  for i in tf.range(x.shape):
    if( x[i] % 2 == 0):
      new_tensor = new_tensor.write(i, y[i])
    else:
      new_tensor = new_tensor.write(i, z[i])
  return new_tensor.stack()

In [0]:
new_tensor = new_tensor_gen(x,y,z)
new_tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([5, 4, 9, 8, 0, 5, 6, 8, 2, 8], dtype=int32)>

# **Task 7**

Given a tensor of arbitrary and unknown shape (but at least one dimension), return 100 if the last dimension has size > 100, 12 if the last dimension has size <= 100 and > 44, and return 0 otherwise.

In [0]:
x = tf.random.uniform([15,20, 6],minval=-10, maxval=10, dtype=tf.dtypes.int32)
def fun(inp_tensor):
  last_dim = inp_tensor.shape[-1]
  print(last_dim)
  if last_dim > 100:
    return 100
  elif (last_dim in tf.range(44,101)):
    return 12
  else:
    return 0

In [0]:
print(fun(x))

6
0


# **Task 8**
As 7., but also create three global counts (integers), where count i should grow by 1 if condition i happened. Run the function from 7. multiple times to test whether your counting works. Now, add a @tf.function decorator to the function from 7. Does your counter still work? If not, why not? Can you change it so it does work?

In [0]:
# Global counters
c1 = tf.Variable(0)
c2 = tf.Variable(0)
c3 = tf.Variable(0)

In [0]:
@tf.function
def fun2(inp_tensor, c1, c2, c3):
  last_dim = inp_tensor.shape[-1]
  if last_dim > 100:
    c1.assign_add(1)
    return 100
  elif (last_dim in range(44,101)):
    c2.assign_add(1)
    return 12
  else:
    c3.assign_add(1)
    return 0

In [0]:
x = tf.zeros([1,1,86])
print(fun2(x, c1,c2,c3))
print(c1)
print(c2)
print(c3)

tf.Tensor(12, shape=(), dtype=int32)
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>


# **Task 9**
Given two 1D tensors of equal length n, create a tensor of shape (n, n) where element i,j is the ith element of the first tensor minus the jth element of the second tensor. No loops! Hint: Tensorflow supports broadcasting much like numpy.

In [0]:
x = tf.random.uniform([3],minval=0, maxval=10, dtype=tf.dtypes.int32)
y = tf.random.uniform([3],minval=0, maxval=10, dtype=tf.dtypes.int32)
@tf.function
def gen_tensor(t1, t2):
  n = t1.shape[0]
  return(tf.subtract(tf.reshape(tf.repeat(t1, repeats=n, axis=0), [n,n]), t2))

In [0]:
gen_tensor(x,y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 7,  5,  5],
       [-1, -3, -3],
       [ 6,  4,  4]], dtype=int32)>

# **Task 10**

Implement dot product attention: You are given a sequence of encoder states h of shape batch x time x features and the last decoder state s of shape batch x features. Compute the attention weights alpha where alpha[:, i] is equal to h[:, i] * s where * is the dot product between vectors (in this case we also have a batch dimension so the dot product should be between the corresponding vectors within the batch). That is, alpha should be of shape batch x time and alpha[:, i] should contain the attention weights for encoder time step i.

![alt text](https://drive.google.com/uc?id=1HtmC8xm5QjgwhcSjzKajo4EcIk2lF5bI)

In [6]:

# this is just a datasets of "bytes" (not understandable)
data = tf.data.TFRecordDataset("skp.tfrecords")


#data.padded_batch
#batched_data = data.padded_batch(batch_size = 128, drop_remainder=True)
# this maps a parser function that properly interprets the bytes over the dataset
# (with fixed sequence length 200)
# if you change the sequence length in preprocessing you also need to change it here
data = data.map(lambda x: parse_seq(x, 200))


#batched_categorical_data = data.padded_batch(batch_size=128, padded_shapes=448,padding_values=0, drop_remainder=True)

# a map from characters to indices
vocab = pickle.load(open("skp_vocab", mode="rb"))
vocab_size = len(vocab)
# inverse mapping: indices to characters
ind_to_ch = {ind: ch for (ch, ind) in vocab.items()}
ch_to_ind = {v: k for k, v in ind_to_ch.items()}
print(vocab)
print(vocab_size)

{'\n': 1, 'C': 2, 'l': 3, '!': 4, '?': 5, 'q': 6, 'f': 7, 't': 8, 'J': 9, 'n': 10, ':': 11, 'i': 12, 'r': 13, 'R': 14, 's': 15, ' ': 16, 'v': 17, 'I': 18, 'V': 19, '-': 20, 'Z': 21, 'X': 22, 'z': 23, 'e': 24, 'U': 25, 'F': 26, 'N': 27, '[': 28, 'm': 29, 'S': 30, 'd': 31, 'O': 32, '3': 33, 'a': 34, ']': 35, 'W': 36, 'c': 37, 'k': 38, 'Y': 39, 'L': 40, 'P': 41, 'w': 42, 'B': 43, "'": 44, 'E': 45, 'x': 46, 'H': 47, 'M': 48, 'u': 49, ',': 50, 'y': 51, 'h': 52, 'Q': 53, '&': 54, 'G': 55, 'b': 56, 'D': 57, '$': 58, 'K': 59, 'T': 60, 'o': 61, '.': 62, 'g': 63, 'j': 64, ';': 65, 'A': 66, 'p': 67, '<S>': 0}
68


In [0]:
batched_vocab_data = data.batch(batch_size=128,drop_remainder=True)
batched_onehotencoded_data = new_data.batch(batch_size=128, drop_remainder=True)

In [0]:

for num, elem in enumerate(data):
  if(num == 4):

    break;
  #print(elem)
  #print(" ====== Creating Labels by taking slices ==========")
  #print(elem[1:])


In [0]:
def onehotencode(ds):
  
  new_data = tf.one_hot(indices = ds, depth = vocab_size)
  return new_data;

new_data = data.map(onehotencode)

In [9]:
cnt = 0
for element in data:
  cnt = cnt+1
print(cnt)

25549


In [0]:
current_decoder_state_fixed = tf.Variable(tf.keras.initializers.GlorotNormal(seed = 1)(shape=[128,63]))
previous_decoder_state_fixed = tf.Variable(tf.keras.initializers.GlorotNormal(seed = 1)(shape=[128,63]))
current_encoder_state = tf.Variable(tf.keras.initializers.GlorotNormal(seed = 1)(shape=[128,63]))
unscaled_attention_matrix = tf.Variable(tf.keras.initializers.GlorotNormal(seed = 1)(shape=[128,200]))
softmax_attention_matrix = tf.Variable(tf.keras.initializers.GlorotNormal(seed = 1)(shape=[128,200]))

In [19]:
previous_decoder_state_fixed

<tf.Variable 'Variable:0' shape=(128, 63) dtype=float32, numpy=
array([[ 0.01473352, -0.05735376,  0.07342789, ...,  0.09645282,
         0.0628942 ,  0.18157996],
       [-0.01305565, -0.04977272,  0.12497865, ...,  0.05449903,
        -0.18177864, -0.06606366],
       [ 0.01745264, -0.21106663, -0.03510231, ..., -0.12910882,
        -0.07065466, -0.04943841],
       ...,
       [ 0.07512955,  0.02983235, -0.08212686, ..., -0.03503273,
        -0.07772417,  0.12510055],
       [ 0.02088889,  0.19565317,  0.06373518, ...,  0.04682589,
        -0.07369351, -0.19658963],
       [-0.18037029, -0.11600257, -0.01586506, ..., -0.07738629,
         0.03209957,  0.07263009]], dtype=float32)>

In [22]:
time_steps=200
#Pick the 4th timestep decoder state of dimension [128, 1]
for batch_num, (x_batch_train, val_data) in enumerate(zip(batched_onehotencoded_data,batched_vocab_data) ):
  print("===== batch number: {}".format(batch_num))
  for time_step in range(time_steps-1):
    if(time_step == 4):
      previous_decoder_state_fixed = val_data[:, time_step]
    #encoder_state_at_current_time_step = x_batch_train[:, time_step, :]
    #print("shape of each time slice: {} ".format(x_t.shape))
    #lbl_batch = val_data[:, time_step+1]
  break;


===== batch number: 0


In [23]:
previous_decoder_state_fixed

<tf.Tensor: shape=(128,), dtype=int32, numpy=
array([15, 12, 37, 52, 16, 16, 12, 16, 12, 49, 56,  4, 42, 38, 17, 16, 52,
       50,  3, 52, 12, 49,  1,  3, 52, 16, 10,  8, 13, 24,  8, 24, 16, 50,
       16, 12, 61, 61, 61, 34, 16, 16, 24, 49, 61, 12, 29, 38,  4, 34, 24,
       52, 63, 60, 13, 13, 42, 47, 24, 51, 16, 16, 50, 61, 52, 24, 61, 24,
       56, 37,  3, 24, 49, 56, 24,  7, 24, 15,  8,  8, 13, 67, 16, 31,  3,
       34, 63, 16, 13, 24, 15, 12, 24, 16, 40, 15, 34, 49, 12, 18, 63, 16,
       12, 24,  8, 13, 34, 10, 18, 16, 16, 30, 61, 10, 24, 66, 15, 14, 49,
       63, 42, 12, 12, 52, 13,  1, 52, 51], dtype=int32)>

In [24]:
onehotencoded_prev_decoder_state = onehotencode(previous_decoder_state_fixed)
onehotencoded_prev_decoder_state

<tf.Tensor: shape=(128, 68), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [40]:
time_steps=200
output_list = []
for batch_num, (x_batch_train, val_data) in enumerate(zip(batched_onehotencoded_data,batched_vocab_data) ):
  print("===== batch number: {}".format(batch_num))
  for time_step in range(time_steps):
    #(128 * 68) dot product (68 * 128) ==> (128, 128)
    curr_timestep_attention_onehot = tf.matmul(a=x_batch_train[:,time_step,:], b=onehotencoded_prev_decoder_state, transpose_b=True)

    #Printing some stuff for checking
    #print(curr_timestep_attention_onehot)
    #print(tf.math.reduce_sum(curr_timestep_attention_onehot, axis=1, keepdims=False, name=None))

    #Convert the onehot encoded output to categorical for attention
    #(128 * 128) === reduce sum on axis 1 to check attention inside same record, using axis zero would take cross records sum
    # (128 * 128) ===> (128 * 1) ==> one attention value per record per timestep
    output_list.append(tf.math.reduce_sum(curr_timestep_attention_onehot, axis=1, keepdims=False, name=None))
    
  unscaled_outputs = tf.stack(output_list,axis = 1)
  print("====== unscaled thing =============")
  print(unscaled_outputs)
  print()
  print(" ===============. softmax thing ===========")
  softmax_output = tf.nn.softmax(unscaled_outputs, axis=1)
  print(softmax_output)
  print()
  print("======== check whether softmax adds to one for final check, it adds to ne approx(numerical multiplier issues in matmul) ===========")
  print(tf.reduce_sum(softmax_output, axis=1))

  #Print the below to check that softmax across axis = 0 doesn't sum to one for final check
  #print(tf.reduce_sum(softmax_output, axis=0))
  break;

===== batch number: 0
====== unscaled thing =============
tf.Tensor(
[[ 0.  0. 11. ... 17.  2.  7.]
 [ 0.  5. 17. ...  7.  7. 14.]
 [ 0.  7.  1. ...  5. 17.  7.]
 ...
 [ 0.  3. 14. ...  3.  7.  5.]
 [ 0.  5. 17. ... 17.  1.  5.]
 [ 0. 17.  5. ...  7.  1.  5.]], shape=(128, 200), dtype=float32)

 ===============. softmax thing ===========
tf.Tensor(
[[1.7862440e-09 1.7862440e-09 1.0694983e-04 ... 4.3146640e-02
  1.3198658e-08 1.9588545e-06]
 [1.3877071e-09 2.0595400e-07 3.3519998e-02 ... 1.5218056e-06
  1.5218056e-06 1.6688624e-03]
 [1.6701229e-09 1.8315121e-06 4.5398649e-09 ... 2.4786820e-07
  4.0341739e-02 1.8315121e-06]
 ...
 [1.4342060e-09 2.8806797e-08 1.7247822e-03 ... 2.8806797e-08
  1.5727978e-06 2.1285504e-07]
 [1.2631630e-09 1.8747001e-07 3.0511642e-02 ... 3.0511642e-02
  3.4336332e-09 1.8747001e-07]
 [1.5965517e-09 3.8564630e-02 2.3694928e-07 ... 1.7508315e-06
  4.3398778e-09 2.3694928e-07]], shape=(128, 200), dtype=float32)

======== check whether softmax adds to one for fin